-- Revoke the unnecessary direct INSERT grant on chat_archive from service_role.
--
-- NOT YET APPLIED when this file was written (2026-08-20). Per supabase/README.md
-- the filename must match what `list_migrations` reports, so rename this file to
-- the version `apply_migration` assigns.
--
-- Found by an external review immediately after
-- 20260820131914_chat_session_persistence.sql applied. chat_append_turn is
-- SECURITY DEFINER, so it runs with the privileges of the function OWNER, not
-- the caller — it never needed service_role to hold INSERT on chat_archive to
-- do its own insert there. That grant is therefore not what makes
-- chat_append_turn work; it is a SECOND, unguarded way for anything holding
-- the service-role key (SupabaseAdminClient — "SERVER-SIDE ONLY", used
-- broadly for admin operations elsewhere in this app) to write a row into
-- chat_archive directly, skipping chat_append_turn's owner/session validation
-- and its atomic pairing with a real chat_messages turn.
--
-- Nothing in this codebase currently does that — chat_archive appears nowhere
-- outside web/services/chat_store.py — so this closes a least-privilege gap,
-- not an active exploit.
--
-- Matches the "revoke all, then grant back only what's needed" shape the base
-- migration already applies to chat_sessions / chat_messages /
-- chat_message_sources, for the same reason (see that migration's "AND THE
-- SERVICE ROLE LOSES DIRECT WRITES TOO" comment). SELECT stays: reads are
-- harmless, and this is symmetry with the sibling tables rather than closing
-- a path anything actually reads through.
--
-- VERIFY AT APPLY TIME: re-run chat_append_turn in a rolled-back transaction
-- (as for the base migration) to confirm the archive insert inside it still
-- succeeds — it must, since SECURITY DEFINER bypasses this grant entirely.
revoke insert on public.chat_archive from service_role;
